### ISSUE TITLE
How to stop it?

### ISSUE THREAD

**Issue by work-bition** [chinchang/superplaceholder.js#18] opened 2018-12-11 15:54 UTC
I wanna stop it when sometimes I need this. Why don't you open the interface of cleanup?

**Comment by chinchang** [comment] 2018-12-11 16:04
duplicate of #11

**Comment by chinchang** [comment] 2018-12-14 14:47
@work-bition By default superplaceholder starts playing when you focus an input. Let's say you stop it with the new interface. Now when you focus that input, what do you expect - Should superplaceholder again start playing or not?

**Closed as completed** 2018-12-14 14:47 UTC
Labels: duplicate, enhancement
